<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\BookRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity
 * @source data/book.jsonl
 */
#[Entity(repositoryClass: BookRepository::class)]
#[MeiliIndex(
	primaryKey: 'bookId',
	filterable: self::FILTERABLE_FIELDS,
	sortable: self::SORTABLE_FIELDS,
	searchable: self::SEARCHABLE_FIELDS,
)]
final class Book
{
	public const FILTERABLE_FIELDS = [
		'bookId',
		'goodreadsBookId',
		'bestBookId',
		'workId',
		'booksCount',
		'languageCode',
		'ratingsCount',
		'workRatingsCount',
		'workTextReviewsCount',
		'ratings1',
		'ratings2',
		'ratings3',
		'ratings4',
		'ratings5',
	];

	public const SORTABLE_FIELDS = [
		'bookId',
		'goodreadsBookId',
		'bestBookId',
		'workId',
		'booksCount',
		'isbn13',
		'originalPublicationYear',
		'averageRating',
		'ratingsCount',
		'workRatingsCount',
		'workTextReviewsCount',
		'ratings1',
		'ratings2',
		'ratings3',
		'ratings4',
		'ratings5',
	];

	public const SEARCHABLE_FIELDS = ['authors'];

	/**
	 * Field: book_id
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 1
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	#[Id]
	public ?int $bookId = null;

	/**
	 * Field: goodreads_book_id
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 2767052
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $goodreadsBookId = null;

	/**
	 * Field: best_book_id
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 2767052
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $bestBookId = null;

	/**
	 * Field: work_id
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 2792775
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $workId = null;

	/**
	 * Field: books_count
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 272
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $booksCount = null;

	/**
	 * Field: isbn
	 * total=9300, nulls=700, distinct=501 (capped)
	 * length: 10 chars
	 * Top/First value: "439023483"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 10, nullable: true)]
	public ?string $isbn = null;

	/**
	 * Field: isbn13
	 * total=9415, nulls=585, distinct=501 (capped)
	 * Top/First value: 9780439023480
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $isbn13 = null;

	/**
	 * Field: authors
	 * total=10000, nulls=0, distinct=501 (capped)
	 * length: 3–742 chars
	 * Top/First value: "Suzanne Collins"
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::TEXT, nullable: true)]
	public ?string $authors = null;

	/**
	 * Field: original_publication_year
	 * total=9979, nulls=21, distinct=293
	 * Top/First value: 2008
	 */
	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $originalPublicationYear = null;

	/**
	 * Field: original_title
	 * total=9410, nulls=590, distinct=501 (capped)
	 * length: 1–196 chars
	 * Top/First value: "The Hunger Games"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 196, nullable: true)]
	public ?string $originalTitle = null;

	/**
	 * Field: title
	 * total=10000, nulls=0, distinct=501 (capped)
	 * length: 2–186 chars
	 * Top/First value: "The Hunger Games (The Hunger Games, #1)"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 186, nullable: true)]
	public ?string $title = null;

	/**
	 * Field: language_code
	 * total=8916, nulls=1084, distinct=25
	 * length: 2–5 chars
	 * Top/First value: "eng"
	 * Facet candidate
	 */
	#[Column(length: 5, nullable: true)]
	public ?string $languageCode = null;

	/**
	 * Field: average_rating
	 * total=10000, nulls=0, distinct=184
	 * Top/First value: 4.34
	 */
	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $averageRating = null;

	/**
	 * Field: ratings_count
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 4780653
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratingsCount = null;

	/**
	 * Field: work_ratings_count
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 4942365
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $workRatingsCount = null;

	/**
	 * Field: work_text_reviews_count
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 155254
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $workTextReviewsCount = null;

	/**
	 * Field: ratings_1
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 66715
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings1 = null;

	/**
	 * Field: ratings_2
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 127936
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings2 = null;

	/**
	 * Field: ratings_3
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 560092
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings3 = null;

	/**
	 * Field: ratings_4
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 1481305
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings4 = null;

	/**
	 * Field: ratings_5
	 * total=10000, nulls=0, distinct=501 (capped)
	 * Top/First value: 2706317
	 * Distinct counting capped in profile.
	 */
	#[Column(type: Types::INTEGER, nullable: true)]
	public ?int $ratings5 = null;

	/**
	 * Field: image_url
	 * total=10000, nulls=0, distinct=501 (capped)
	 * length: 52–88 chars
	 * Top/First value: "https://images.gr-assets.com/books/1447303603m/2767052.jpg"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 88, nullable: true)]
	public ?string $imageUrl = null;

	/**
	 * Field: small_image_url
	 * total=10000, nulls=0, distinct=501 (capped)
	 * length: 52–86 chars
	 * Top/First value: "https://images.gr-assets.com/books/1447303603s/2767052.jpg"
	 * Distinct counting capped in profile.
	 */
	#[Column(length: 86, nullable: true)]
	public ?string $smallImageUrl = null;
}
