<?php

declare(strict_types=1);

namespace App\Entity;

use App\Repository\MovieRepository;
use DateTimeImmutable;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping\Column;
use Doctrine\ORM\Mapping\Entity;
use Doctrine\ORM\Mapping\Id;
use Survos\MeiliBundle\Metadata\Facet;
use Survos\MeiliBundle\Metadata\FacetWidget;
use Survos\MeiliBundle\Metadata\MeiliIndex;

/**
 * @generated by code:entity
 */
#[Entity(repositoryClass: MovieRepository::class)]
#[MeiliIndex(
    searchable: ['title','overview'],
    filterable: ['year', 'budget', 'genres'],
    sortable: ['year', 'budget'],
//    embedders: ['small','best']
)]
final class Movie
{
	#[Column(type: Types::INTEGER, nullable: true)]
	#[Id]
	public ?int $id = null;

	#[Column(length: 255, nullable: true)]
	public ?string $title = null;

	#[Column(Types::TEXT, nullable: true)]
	public ?string $overview = null;

	#[Column(length: 255, nullable: true)]
	public ?string $tags = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $genres = null;

	#[Column(length: 255, nullable: true)]
	public ?string $director = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $actors = null;

	#[Column(type: Types::JSON, options: ['jsonb' => true], nullable: true)]
	public ?array $characters = null;

	#[Column(type: Types::INTEGER, nullable: true)]
    #[Facet(widget: FacetWidget::RangeSlider)]
	public ?int $year = null;

	#[Column(type: Types::INTEGER, nullable: true)]
    #[Facet(widget: FacetWidget::RangeSlider)]
	public ?int $votes = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $rating = null;

	#[Column(type: Types::FLOAT, nullable: true)]
	public ?float $popularity = null;

	#[Column(type: Types::INTEGER, nullable: true)]
    #[Facet(widget: FacetWidget::RangeSlider)]
	public ?int $budget = null;

	#[Column(type: Types::TEXT,nullable: true)]
	public ?string $posterUrl = null;
}
